INSERT INTO BUILDING(ID, NAME, NB_OF_FLOORS) VALUES(-20, 'Building1', 5);
INSERT INTO BUILDING(ID, NAME, NB_OF_FLOORS) VALUES(-19, 'Building2', 5);

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1, -20);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1, - 20);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);

INSERT INTO RINGER(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 20, 'ON', -10);
INSERT INTO RINGER(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 10, 'OFF', -10);